GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjczODYwNDExLCJleHAiOjE2NzM4NjA0MjZ9.HrmWzW_N0kBPl1BNvVJAOfQLrAJtYOwBOY7dsytJNtg
###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Iqbal Kurnia",
  "email": "iqbal@gmail.com",
  "password": "123456",
  "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin"
}

###
GET http://localhost:5000/token

###
DELETE  http://localhost:5000/logout
